
-- Re-create supplier_orders table to ensure it matches our frontend needs
DROP TABLE IF EXISTS supplier_orders CASCADE;

CREATE TABLE supplier_orders (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    supplier_id bigint references suppliers(id),
    supplier_name text, -- Backup/Display name
    items jsonb not null, -- Stores array of { itemId, name, qty, unit }
    note text,
    status text default 'sent' check (status in ('sent', 'received', 'cancelled')),
    delivery_date date
);
